using DevToys.Api;
using System.ComponentModel.Composition;
using static DevToys.Api.GUI;
using DevToys.JsonToGo.Converters;

namespace DevToys.JsonToGo;

[Export(typeof(IGuiTool))]
[Name("JsonToGo")]
[ToolDisplayInformation(
    IconFontName = "FluentSystemIcons",
    IconGlyph = '\uf39a',
    GroupName = PredefinedCommonToolGroupNames.Converters,
    ResourceManagerAssemblyIdentifier = nameof(JsonToGoAssemblyIdentifier),
    ResourceManagerBaseName = "DevToys.JsonToGo.JsonToGoExtension",
    ShortDisplayTitleResourceName = nameof(JsonToGoExtension.ShortDisplayTitle),
    LongDisplayTitleResourceName = nameof(JsonToGoExtension.LongDisplayTitle),
    DescriptionResourceName = nameof(JsonToGoExtension.Description),
    AccessibleNameResourceName = nameof(JsonToGoExtension.AccessibleName))]
internal sealed class JsonToGoGui : IGuiTool
{
    private readonly IUIMultiLineTextInput _inputTextArea = MultiLineTextInput("json-to-go-input-text-area");
    private readonly IUIMultiLineTextInput _outputTextArea = MultiLineTextInput("json-to-go-output-text-area");
    private readonly IUISingleLineTextInput _structNameInput = SingleLineTextInput("json-to-go-struct-name");
    private readonly string _defaultStructName = "AutoGenerated";

    [Import] private ISettingsProvider _settingsProvider = null!;
    private readonly IUISetting _unknownTypeSetting = Setting();

    private readonly SettingDefinition<GoTypes> _unknownTypeOption
        = new(
            name: $"{nameof(JsonToGoGui)}.{nameof(_unknownTypeOption)}",
            defaultValue: GoTypes.Any);

    private readonly SettingDefinition<bool> _optionalField
        = new(
            name: $"{nameof(JsonToGoGui)}.{nameof(_optionalField)}",
            defaultValue: false);

    private bool _enableOptionalField = false;

    private enum GridRows
    {
        Header,
        Content,
        Footer
    }

    private enum GridColumns
    {
        Content
    }


    public UIToolView View =>
        new UIToolView(
            isScrollable: true,
            Grid()
                .ColumnLargeSpacing()
                .RowLargeSpacing()
                .Rows(
                    (GridRows.Header, Auto),
                    (GridRows.Content, new UIGridLength(1, UIGridUnitType.Fraction))
                )
                .Columns(
                    (GridColumns.Content, new UIGridLength(1, UIGridUnitType.Fraction))
                )
                .Cells(
                    Cell(
                        GridRows.Header,
                        GridColumns.Content,
                        Stack()
                            .Vertical()
                            .WithChildren(
                                Label().Text("Configuration"),
                                _structNameInput
                                    .Title("Struct Name")
                                    .Text(_defaultStructName)
                                    .OnTextChanged(OnStructNameChanged),
                                SettingGroup()
                                    .Title("Advanced")
                                    .Icon("FluentSystemIcons", '\uf6a8')
                                    .WithSettings(
                                        _unknownTypeSetting
                                            .Icon("FluentSystemIcons", '\uf4a4')
                                            .Title("Unknown Type")
                                            .Handle(
                                                _settingsProvider,
                                                _unknownTypeOption,
                                                OnUnknownTypeOptionChanged,
                                                Item("any", GoTypes.Any),
                                                Item("*string", GoTypes.StringPtr),
                                                Item("interface{}", GoTypes.Interface)
                                            ),
                                        Setting()
                                            .Icon("FluentSystemIcons", '\uf4a4')
                                            .Title("Optional Field")
                                            .Handle(
                                                _settingsProvider,
                                                _optionalField,
                                                OnEnableOptionalFieldsChanged
                                            )
                                    )
                            )
                    ),
                    Cell(
                        GridRows.Content,
                        GridColumns.Content,
                        SplitGrid()
                            .Vertical()
                            .WithLeftPaneChild(
                                _inputTextArea
                                    .Title("Input(JSON)")
                                    .Language("json")
                                    .OnTextChanged(OnInputTextChanged)
                            )
                            .WithRightPaneChild(
                                _outputTextArea
                                    .Title("Output(Go)")
                                    .Language("go")
                                    .ReadOnly()
                                    .Extendable()
                            )
                    ))
        );

    public void OnDataReceived(string dataTypeName, object? parsedData)
    {
        throw new NotImplementedException();
    }

    private void OnInputTextChanged(string inputText)
    {
        Convert();
    }

    private void Convert()
    {
        if (string.IsNullOrEmpty(_inputTextArea.Text))
        {
            _outputTextArea.Text(string.Empty);
            return;
        }

        var structName = _structNameInput.Text;
        if (string.IsNullOrEmpty(structName))
        {
            structName = _defaultStructName;
        }

        var unknownTypeOption = _settingsProvider.GetSetting(_unknownTypeOption);
        try
        {
            var converter = new JsonToGoConverter(_inputTextArea.Text, structName, unknownTypeOption,
                _enableOptionalField);
            _outputTextArea.Text(converter.Convert());
        }
        catch
        {
            _outputTextArea.Text("Please provide a valid JSON");
        }
    }

    private void OnStructNameChanged(string structName)
    {
        Convert();
    }

    private void OnUnknownTypeOptionChanged(GoTypes goType)
    {
        Convert();
    }

    private void OnEnableOptionalFieldsChanged(bool isEnabled)
    {
        _enableOptionalField = isEnabled;
        Convert();
    }
}